apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: scheduler-ns
spec:
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
